trigger:
  branches:
    include:
      - master

pr: none # pipeline ide dvaput bez PR constraint

pool:
  name: Default

resources:
  repositories:
    - repository: self
      trigger: none

variables:
  workingDirectory: '$(System.DefaultWorkingDirectory)'

jobs:
- job: Build_Angular  
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js (if missing)'
    condition: eq(variables['Agent.OS'], 'Windows_NT')

  - script: node --version && npm --version
    displayName: 'Check Node/npm versions'

  - script: npm install -D @angular/cli
    displayName: 'Install Angular CLI'
    workingDirectory: $(workingDirectory)

  - script: npm ci
    displayName: 'Install dependencies'
    workingDirectory: $(workingDirectory)

  - script: ng build --prod
    displayName: 'Build Angular Production'
    workingDirectory: $(workingDirectory)

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(workingDirectory)/dist'
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    displayName: 'Archive build artifacts'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'angular_build'
    displayName: 'Publish Build Artifacts'
